### ISSUE TITLE
Doesn't work in CANVAS mode on Chrome

### ISSUE THREAD

**Issue by RollinSafary** [koreezgames/phaser3-ninepatch-plugin#10]
## Expected Behavior

must work as in WEBGL

## Current Behavior

doesn't render any thing, or rendering just parts of source image
## Possible Solution

seems that some functions doesn't work on Chrome

## Steps to Reproduce (for bugs)

1. set in game configs `type: Phaser.CANVAS`
2. try to use NinePatch on any image

## Context

doesn't work on Chrome browser
![screen shot 2018-08-02 at 3 02 46 pm](https://user-images.githubusercontent.com/30594036/43580075-2e2585a0-9665-11e8-9827-c1c82a317436.png)

but work on Safari
![screen shot 2018-08-02 at 2 55 57 pm](https://user-images.githubusercontent.com/30594036/43580005-fb773522-9664-11e8-8fb6-c6775e47b376.png)

## Your Environment

* Version used: 1.1.3
* tested on Version 67.0.3396.99 (Official Build) (64-bit) 
* Mac OS 10.13.4
* [link](https://github.com/koreezgames/phaser3-ninepatch-plugin/blob/master/example/index.ts)

# Stack trace

No errors

**Comment by saqsun** [comment]
this is phaser issue not the plugin
