### ISSUE TITLE
addToScene is required 

### ISSUE THREAD

**Issue by RollinSafary** [koreezgames/phaser3-ninepatch-plugin#8]
## Expected Behavior

All the phasers' game objects have optional argument `addToScene` - not required 

## Current Behavior

`this.make.ninePatch(config, addToScene) requires `addToScene`

## Possible Solution

just make it optional

## Steps to Reproduce (for bugs)

1. try to make ninePatch via `this.make.ninePatch`

## Your Environment

* Version 1.1.3:

**Comment by saqsun** [comment]
fixed
